version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm run test

  build-and-push:
    docker:
      - image: anusuyadevi2024/circleci_sample:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t your-docker-username/your-docker-repo:latest .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-docker-username/your-docker-repo:latest

workflows:
  version: 2
  build:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
