version: 2.1

orbs:
  docker: circleci/docker@24.0.7

jobs:
  test:
    docker:
      - image: mycirclecisampleapp:latest 
    steps:
      - run:
          name: Run Tests
          command: |
            npm test

  build-and-push:
    docker:
      - image: anusuyadevi2024/circleci_sample:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t your-docker-username/your-docker-repo:latest .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-docker-username/your-docker-repo:latest

workflows:
  version: 2
  build:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
