version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test

  publish:
    # executor: docker/docker
    # steps:
    #   - setup_remote_docker
    #   - checkout
    #   - docker/check
    #   - docker/build:
    #       image: anusuyadevi2024/circleci_sample
    #       tag:1.0.0
    #   - docker/push:
    #       image: anusuyadevi2024/circleci_sample
    #       tag:1.0.0
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: publish Docker Image
          command: |
            docker build -t anusuyadevi2024/circleci_sample:v1.0.1 .
            echo "DOCKER_USERNAME: $DOCKER_USERNAME"
            echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push anusuyadevi2024/circleci_sample:v1.0.1
  # deploy:
  #   docker:
  #       - image: cimg/node:16.10
  #   steps:
  #       - setup_remote_docker
  #       - heroku/install
  #       - checkout
  #       - run:
  #           name: Heroku Container Push
  #           command: |
  #               heroku container:login
  #               heroku container:push web -a anusuyadevi-su-devops
  #               heroku container:release web -a anusuyadevi-su-devops
  pull-and-deploy:
    docker:
      -image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - docker/pull:
          images: anusuyadevi2024/circleci_sample:v1.0.1
      - run:
          name: Heroku Container Push With Image From Docker Hub
          command: |
            heroku container:login
            docker tag anusuyadevi2024/circleci_sample:v1.0.1 registry.heroku.com/anusuyadevi-su-devops/web
            # format ---docker tag <image name from docker hub> registry.heroku.com/<app-name>/web
            docker push registry.heroku.com/anusuyadevi-su-devops/web
            # format ---docker push registry.heroku.com/<app-name>/web
            heroku container:release web -a anusuyadevi-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - publish
      - pull-and-deploy:
          requires:
            - publish
